### PR TITLE
Update the links to the Document Review page

### PR DESCRIPTION
**Pull request by xfq**

### CODE REVIEW

**Review by fantasai — CHANGES_REQUESTED** [review]
I think you wanted https://www.w3.org/Guide/documentreview no?

**Comment by xfq** [comment]
@fantasai That URL did not exist when I created this PR. I will update the PR.

**Comment by xfq** [comment]
It seems that a lot of text in this document has been changed (my PR was against the Process 2019 version, but the current HEAD is the Process 2020 version). Comparing with resolving the merge conflict, I think it's faster to close this PR and create a new one.

**Comment by xfq** [comment]
See https://github.com/w3c/transitions/pull/267 for the new PR.

**Pull request closed without merging**
